import { Position } from 'reactflow';
import { 
  Sparkles,
  Palette,
  Bot,
  Settings,
  CheckCircle,
  Brain,
  Search,
  Layers,
  Wand2,
  Image,
  Crop,
  Filter,
  Zap,
  Target,
  Database,
  BarChart3,
  FileImage,
  Sliders,
  Eye,
  Download
} from "lucide-react";

export const getImageNodes = (isDark: boolean) => [
  // Prompt Analysis & Enhancement Pipeline (Top Row) - Clean horizontal flow
  {
    id: '1',
    type: 'inputNode',
    data: { label: 'Text Prompt', inputValue: '' },
    position: { x: 0, y: 190 },
    sourcePosition: Position.Right,
    draggable: true,
  },
  {
    id: '2',
    type: 'processNode',
    data: { label: 'Prompt Analysis', icon: Brain },
    position: { x: 270, y: 180 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '3',
    type: 'processNode',
    data: { label: 'Keyword Extraction', icon: Search },
    position: { x: 490, y: 180 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '4',
    type: 'processNode',
    data: { label: 'Prompt Enhancement', icon: Sparkles },
    position: { x: 710, y: 180 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  
  // Configuration Pipeline (Second Row) - Left to right flow
  {
    id: '8',
    type: 'processNode',
    data: { label: 'Negative Prompts', icon: Target },
    position: { x: 0, y: 390 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '9',
    type: 'processNode',
    data: { label: 'Aspect Ratio', icon: Crop },
    position: { x: 270, y: 300 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '5',
    type: 'processNode',
    data: { label: 'Style Selection', icon: Palette },
    position: { x: 490, y: 300 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '6',
    type: 'processNode',
    data: { label: 'Model Selection', icon: Bot },
    position: { x: 710, y: 300 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '7',
    type: 'processNode',
    data: { label: 'Parameter Tuning', icon: Sliders },
    position: { x: 930, y: 300 },
    sourcePosition: Position.Bottom,
    targetPosition: Position.Left,
    draggable: true,
  },
  
  // AI Generation Pipeline (Third Row) - Right to left flow for better connections
  {
    id: '10',
    type: 'processNode',
    data: { label: 'Multi-Model Gen', icon: Layers },
    position: { x: 930, y: 420 },
    sourcePosition: Position.Left,
    targetPosition: Position.Top,
    draggable: true,
  },
  {
    id: '11',
    type: 'processNode',
    data: { label: 'Variation Creation', icon: Wand2 },
    position: { x: 710, y: 420 },
    sourcePosition: Position.Left,
    targetPosition: Position.Right,
    draggable: true,
  },
  {
    id: '12',
    type: 'processNode',
    data: { label: 'Quality Scoring', icon: BarChart3 },
    position: { x: 490, y: 420 },
    sourcePosition: Position.Left,
    targetPosition: Position.Right,
    draggable: true,
  },
  {
    id: '13',
    type: 'processNode',
    data: { label: 'Best Selection', icon: Eye },
    position: { x: 270, y: 420 },
    sourcePosition: Position.Bottom,
    targetPosition: Position.Right,
    draggable: true,
  },
  
  // Post-Processing Pipeline (Fourth Row) - Clean left to right flow
  {
    id: '14',
    type: 'processNode',
    data: { label: 'Upscaling', icon: Zap },
    position: { x: 270, y: 540 },
    sourcePosition: Position.Right,
    targetPosition: Position.Top,
    draggable: true,
  },
  {
    id: '15',
    type: 'processNode',
    data: { label: 'Enhancement', icon: Filter },
    position: { x: 490, y: 540 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '16',
    type: 'processNode',
    data: { label: 'Format Export', icon: FileImage },
    position: { x: 710, y: 540 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '17',
    type: 'processNode',
    data: { label: 'Metadata Save', icon: Database },
    position: { x: 930, y: 540 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  
  // Final Output
  {
    id: '18',
    type: 'outputNode',
    data: { label: 'Final Gallery' },
    position: { x: 1200, y: 250 },
    targetPosition: Position.Left,
    draggable: true,
  },
];
