import { Position } from 'reactflow';
import { 
  PenTool,
  Mic,
  Palette,
  Film,
  Image,
  Upload,
  Lightbulb,
  Brain,
  Search,
  Database,
  FileSpreadsheet,
  HardDrive,
  BarChart3,
  CheckCircle,
  Calendar,
  Tags,
  TrendingUp,
  Globe
} from "lucide-react";

export const getYoutubeNodes = (isDark: boolean) => [
  // Idea Generation & Research Pipeline (Top Row) - Moved down and compacted
  {
    id: '1',
    type: 'inputNode',
    data: { label: 'Content Niche', inputValue: '' },
    position: { x: -30, y: 330 },
    sourcePosition: Position.Right,
    draggable: true,
  },
  {
    id: '2',
    type: 'processNode',
    data: { label: 'Trend Analysis', icon: TrendingUp },
    position: { x: 270, y: 150 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '3',
    type: 'processNode',
    data: { label: 'Idea Generation', icon: Lightbulb },
    position: { x: 490, y: 150 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '4',
    type: 'processNode',
    data: { label: 'Keyword Research', icon: Search },
    position: { x: 710, y: 150 },
    sourcePosition: Position.Bottom,
    targetPosition: Position.Left,
    draggable: true,
  },
  
  // Content Planning & Data Storage (Second Row) - Compacted horizontally
  {
    id: '5',
    type: 'processNode',
    data: { label: 'Content Planning', icon: Calendar },
    position: { x: 710, y: 240 },
    sourcePosition: Position.Right,
    targetPosition: Position.Top,
    draggable: true,
  },
  {
    id: '6',
    type: 'processNode',
    data: { label: 'Save to Sheets', icon: FileSpreadsheet },
    position: { x: 990, y: 170 },
    sourcePosition: Position.Bottom,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '7',
    type: 'processNode',
    data: { label: 'Script Generation', icon: PenTool },
    position: { x: 270, y: 240 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '8',
    type: 'processNode',
    data: { label: 'SEO Optimization', icon: BarChart3 },
    position: { x: 490, y: 240 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  
  // Content Creation Pipeline (Third Row) - Compacted
  {
    id: '9',
    type: 'processNode',
    data: { label: 'Voice Synthesis', icon: Mic },
    position: { x: 270, y: 340 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '10',
    type: 'processNode',
    data: { label: 'Image Generation', icon: Palette },
    position: { x: 490, y: 340 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '11',
    type: 'processNode',
    data: { label: 'Save to Drive', icon: HardDrive },
    position: { x: 710, y: 340 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '12',
    type: 'processNode',
    data: { label: 'Video Assembly', icon: Film },
    position: { x: 930, y: 340 },
    sourcePosition: Position.Bottom,
    targetPosition: Position.Left,
    draggable: true,
  },
  
  // Publishing & Analytics Pipeline (Fourth Row) - Compacted to fit viewport
  {
    id: '13',
    type: 'processNode',
    data: { label: 'Thumbnail Design', icon: Image },
    position: { x: 270, y: 460 },
    sourcePosition: Position.Right,
    targetPosition: Position.Top,
    draggable: true,
  },
  {
    id: '14',
    type: 'processNode',
    data: { label: 'Metadata & Tags', icon: Tags },
    position: { x: 500, y: 460 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '15',
    type: 'processNode',
    data: { label: 'YouTube Upload', icon: Upload },
    position: { x: 710, y: 460 },
    sourcePosition: Position.Bottom,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '16',
    type: 'processNode',
    data: { label: 'Performance Tracking', icon: BarChart3 },
    position: { x: 270, y: 580 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  
  // Final Output & Analytics - Positioned to fit in viewport
  {
    id: '17',
    type: 'processNode',
    data: { label: 'Analytics Update', icon: Database },
    position: { x: 530, y: 580 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    draggable: true,
  },
  {
    id: '18',
    type: 'outputNode',
    data: { label: 'Published & Tracked' },
    position: { x: 950, y: 580 },
    targetPosition: Position.Left,
    draggable: true,
  },
];
