import { Brand } from "@/types/brand";

const brandsData: Brand[] = [
  {
    id: 1,
    name: "OpenAI",
    href: "https://openai.com",
    image: "/images/tools/openai.svg",
    imageLight: "/images/tools/openai.svg",
  },
  {
    id: 2,
    name: "Anthropic",
    href: "https://anthropic.com",
    image: "/images/tools/anthropic.svg",
    imageLight: "/images/tools/anthropic.svg",
  },
  {
    id: 3,
    name: "Hugging Face",
    href: "https://huggingface.co",
    image: "/images/tools/huggingface.svg",
    imageLight: "/images/tools/huggingface.svg",
  },
  {
    id: 4,
    name: "LangChain",
    href: "https://langchain.com",
    image: "/images/tools/langchain.svg",
    imageLight: "/images/tools/langchain.svg",
  },
  {
    id: 5,
    name: "N8N",
    href: "https://n8n.io",
    image: "/images/tools/n8n.svg",
    imageLight: "/images/tools/n8n.svg",
  },
  {
    id: 6,
    name: "Zapier",
    href: "https://zapier.com",
    image: "/images/tools/zapier.svg",
    imageLight: "/images/tools/zapier.svg",
  },
  {
    id: 7,
    name: "Google Gemini",
    href: "https://gemini.google.com",
    image: "/images/tools/googlegemini.svg",
    imageLight: "/images/tools/googlegemini.svg",
  },
  {
    id: 8,
    name: "Perplexity",
    href: "https://perplexity.ai",
    image: "/images/tools/perplexity.svg",
    imageLight: "/images/tools/perplexity.svg",
  },
  {
    id: 9,
    name: "Ollama",
    href: "https://ollama.ai",
    image: "/images/tools/ollama-icon.svg",
    imageLight: "/images/tools/ollama-icon.svg",
  },
  {
    id: 10,
    name: "Docker",
    href: "https://docker.com",
    image: "/images/tools/docker.svg",
    imageLight: "/images/tools/docker.svg",
  },
  {
    id: 11,
    name: "Python",
    href: "https://python.org",
    image: "/images/tools/python.svg",
    imageLight: "/images/tools/python.svg",
  },
  {
    id: 12,
    name: "Next.js",
    href: "https://nextjs.org",
    image: "/images/tools/nextdotjs.svg",
    imageLight: "/images/tools/nextdotjs.svg",
  },
  {
    id: 13,
    name: "React",
    href: "https://react.dev",
    image: "/images/tools/react.svg",
    imageLight: "/images/tools/react.svg",
  },
  {
    id: 14,
    name: "TypeScript",
    href: "https://typescriptlang.org",
    image: "/images/tools/typescript.svg",
    imageLight: "/images/tools/typescript.svg",
  },
  {
    id: 15,
    name: "Node.js",
    href: "https://nodejs.org",
    image: "/images/tools/nodedotjs.svg",
    imageLight: "/images/tools/nodedotjs.svg",
  },
  {
    id: 16,
    name: "PostgreSQL",
    href: "https://postgresql.org",
    image: "/images/tools/postgresql.svg",
    imageLight: "/images/tools/postgresql.svg",
  },
  {
    id: 17,
    name: "MongoDB",
    href: "https://mongodb.com",
    image: "/images/tools/mongodb.svg",
    imageLight: "/images/tools/mongodb.svg",
  },
  {
    id: 18,
    name: "Supabase",
    href: "https://supabase.com",
    image: "/images/tools/supabase.svg",
    imageLight: "/images/tools/supabase.svg",
  },
];

export default brandsData;
