import { Flow } from "@/types/flow";

const flowsData: Flow[] = [
  {
    id: 1,
    title: "Intelligent File Analysis System",
    paragraph: "Automated document processing and analysis system that extracts insights from various file formats including PDFs, Word documents, spreadsheets, and images with 95% accuracy.",
    image: "/images/blog/blog-01.jpg",
    author: {
      name: "AI Team",
      image: "/images/blog/author-01.png",
      designation: "Automation Specialist",
    },
    tags: ["Document Processing"],
    publishDate: "2025",
    category: "Document Processing",
    complexity: "Medium",
    timeToImplement: "2-3 weeks",
    roi: "300% ROI",
    technologies: ["Python", "TensorFlow", "OCR", "NLP", "PostgreSQL", "React"],
    flowData: {
      nodes: [
        {
          id: '1',
          type: 'input',
          data: { label: 'Document Upload' },
          position: { x: 50, y: 100 },
        },
        {
          id: '2',
          data: { label: 'Format Detection' },
          position: { x: 250, y: 100 },
        },
        {
          id: '3',
          data: { label: 'OCR Processing' },
          position: { x: 450, y: 100 },
        },
        {
          id: '4',
          data: { label: 'NLP Analysis' },
          position: { x: 650, y: 100 },
        },
        {
          id: '5',
          data: { label: 'Data Extraction' },
          position: { x: 250, y: 250 },
        },
        {
          id: '6',
          data: { label: 'Classification' },
          position: { x: 450, y: 250 },
        },
        {
          id: '7',
          type: 'output',
          data: { label: 'Insights Dashboard' },
          position: { x: 650, y: 250 },
        },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3' },
        { id: 'e3-4', source: '3', target: '4' },
        { id: 'e2-5', source: '2', target: '5' },
        { id: 'e5-6', source: '5', target: '6' },
        { id: 'e6-7', source: '6', target: '7' },
        { id: 'e4-7', source: '4', target: '7' },
      ],
    },
  },
  {
    id: 2,
    title: "Custom AI RAG Support System",
    paragraph: "Enterprise-grade AI chatbot trained on company knowledge base to handle Level 1 and Level 2 support tickets automatically with 80% resolution rate.",
    image: "/images/blog/blog-02.jpg",
    author: {
      name: "RAG Team",
      image: "/images/blog/author-02.png",
      designation: "AI Engineer",
    },
    tags: ["Customer Support"],
    publishDate: "2025",
    category: "Customer Support",
    complexity: "High",
    timeToImplement: "4-6 weeks",
    roi: "250% ROI",
    technologies: ["OpenAI GPT-4", "LangChain", "Pinecone", "FastAPI", "React", "WebSocket"],
    flowData: {
      nodes: [
        {
          id: '1',
          type: 'input',
          data: { label: 'Customer Query' },
          position: { x: 50, y: 100 },
        },
        {
          id: '2',
          data: { label: 'Query Processing' },
          position: { x: 250, y: 100 },
        },
        {
          id: '3',
          data: { label: 'Knowledge Search' },
          position: { x: 450, y: 100 },
        },
        {
          id: '4',
          data: { label: 'Context Retrieval' },
          position: { x: 650, y: 100 },
        },
        {
          id: '5',
          data: { label: 'Response Generation' },
          position: { x: 250, y: 250 },
        },
        {
          id: '6',
          data: { label: 'Quality Check' },
          position: { x: 450, y: 250 },
        },
        {
          id: '7',
          type: 'output',
          data: { label: 'AI Response' },
          position: { x: 650, y: 250 },
        },
        {
          id: '8',
          type: 'output',
          data: { label: 'Escalate to Human' },
          position: { x: 450, y: 350 },
        },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3' },
        { id: 'e3-4', source: '3', target: '4' },
        { id: 'e4-5', source: '4', target: '5' },
        { id: 'e5-6', source: '5', target: '6' },
        { id: 'e6-7', source: '6', target: '7' },
        { id: 'e6-8', source: '6', target: '8' },
      ],
    },
  },
  {
    id: 3,
    title: "Automated Email Marketing Pipeline",
    paragraph: "Intelligent email marketing system that personalizes content, optimizes send times, and automatically segments audiences based on behavior with 45% higher open rates.",
    image: "/images/blog/blog-03.jpg",
    author: {
      name: "Marketing AI",
      image: "/images/blog/author-03.png",
      designation: "Marketing Automation Expert",
    },
    tags: ["Marketing Automation"],
    publishDate: "2025",
    category: "Marketing Automation",
    complexity: "Medium",
    timeToImplement: "3-4 weeks",
    roi: "180% ROI",
    technologies: ["Python", "Scikit-learn", "SendGrid API", "Redis", "PostgreSQL", "React"],
    flowData: {
      nodes: [
        {
          id: '1',
          type: 'input',
          data: { label: 'Customer Data' },
          position: { x: 50, y: 100 },
        },
        {
          id: '2',
          data: { label: 'Behavior Analysis' },
          position: { x: 250, y: 100 },
        },
        {
          id: '3',
          data: { label: 'Segmentation' },
          position: { x: 450, y: 100 },
        },
        {
          id: '4',
          data: { label: 'Content Personalization' },
          position: { x: 650, y: 100 },
        },
        {
          id: '5',
          data: { label: 'Send Time Optimization' },
          position: { x: 250, y: 250 },
        },
        {
          id: '6',
          data: { label: 'Email Delivery' },
          position: { x: 450, y: 250 },
        },
        {
          id: '7',
          data: { label: 'Performance Tracking' },
          position: { x: 650, y: 250 },
        },
        {
          id: '8',
          type: 'output',
          data: { label: 'Campaign Analytics' },
          position: { x: 450, y: 350 },
        },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3' },
        { id: 'e3-4', source: '3', target: '4' },
        { id: 'e4-5', source: '4', target: '5' },
        { id: 'e5-6', source: '5', target: '6' },
        { id: 'e6-7', source: '6', target: '7' },
        { id: 'e7-8', source: '7', target: '8' },
      ],
    },
  },
  {
    id: 4,
    title: "Predictive Maintenance System",
    paragraph: "IoT-enabled system that monitors equipment health, predicts failures, and automatically schedules maintenance to prevent costly downtime with 70% reduction in unplanned outages.",
    image: "/images/blog/blog-01.jpg",
    author: {
      name: "IoT Team",
      image: "/images/blog/author-01.png",
      designation: "IoT Specialist",
    },
    tags: ["IoT & Monitoring"],
    publishDate: "2025",
    category: "IoT & Monitoring",
    complexity: "High",
    timeToImplement: "6-8 weeks",
    roi: "400% ROI",
    technologies: ["Python", "TensorFlow", "InfluxDB", "Grafana", "MQTT", "Docker"],
    flowData: {
      nodes: [
        {
          id: '1',
          type: 'input',
          data: { label: 'IoT Sensors' },
          position: { x: 50, y: 100 },
        },
        {
          id: '2',
          data: { label: 'Data Collection' },
          position: { x: 250, y: 100 },
        },
        {
          id: '3',
          data: { label: 'Real-time Processing' },
          position: { x: 450, y: 100 },
        },
        {
          id: '4',
          data: { label: 'Anomaly Detection' },
          position: { x: 650, y: 100 },
        },
        {
          id: '5',
          data: { label: 'Failure Prediction' },
          position: { x: 250, y: 250 },
        },
        {
          id: '6',
          data: { label: 'Maintenance Scheduling' },
          position: { x: 450, y: 250 },
        },
        {
          id: '7',
          type: 'output',
          data: { label: 'Work Orders' },
          position: { x: 650, y: 250 },
        },
        {
          id: '8',
          type: 'output',
          data: { label: 'Alert Dashboard' },
          position: { x: 450, y: 350 },
        },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3' },
        { id: 'e3-4', source: '3', target: '4' },
        { id: 'e4-5', source: '4', target: '5' },
        { id: 'e5-6', source: '5', target: '6' },
        { id: 'e6-7', source: '6', target: '7' },
        { id: 'e6-8', source: '6', target: '8' },
      ],
    },
  },
  {
    id: 5,
    title: "Intelligent Inventory Management",
    paragraph: "AI-powered inventory system that predicts demand, optimizes stock levels, and automates reordering to minimize costs while preventing stockouts with 30% cost reduction.",
    image: "/images/blog/blog-02.jpg",
    author: {
      name: "Supply Chain AI",
      image: "/images/blog/author-02.png",
      designation: "Supply Chain Expert",
    },
    tags: ["Supply Chain"],
    publishDate: "2025",
    category: "Supply Chain",
    complexity: "Medium",
    timeToImplement: "3-5 weeks",
    roi: "220% ROI",
    technologies: ["Python", "Prophet", "PostgreSQL", "Apache Kafka", "Redis", "Vue.js"],
    flowData: {
      nodes: [
        {
          id: '1',
          type: 'input',
          data: { label: 'Sales Data' },
          position: { x: 50, y: 100 },
        },
        {
          id: '2',
          data: { label: 'Demand Forecasting' },
          position: { x: 250, y: 100 },
        },
        {
          id: '3',
          data: { label: 'Stock Optimization' },
          position: { x: 450, y: 100 },
        },
        {
          id: '4',
          data: { label: 'Reorder Point Calculation' },
          position: { x: 650, y: 100 },
        },
        {
          id: '5',
          data: { label: 'Automated Ordering' },
          position: { x: 250, y: 250 },
        },
        {
          id: '6',
          data: { label: 'Supplier Management' },
          position: { x: 450, y: 250 },
        },
        {
          id: '7',
          type: 'output',
          data: { label: 'Inventory Dashboard' },
          position: { x: 650, y: 250 },
        },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3' },
        { id: 'e3-4', source: '3', target: '4' },
        { id: 'e4-5', source: '4', target: '5' },
        { id: 'e5-6', source: '5', target: '6' },
        { id: 'e6-7', source: '6', target: '7' },
      ],
    },
  },
  {
    id: 6,
    title: "Social Media Automation Hub",
    paragraph: "AI-driven social media management system that creates content, schedules posts, analyzes engagement, and responds to comments across multiple platforms automatically.",
    image: "/images/blog/blog-03.jpg",
    author: {
      name: "Social AI",
      image: "/images/blog/author-03.png",
      designation: "Social Media Automation Expert",
    },
    tags: ["Social Media"],
    publishDate: "2025",
    category: "Social Media Automation",
    complexity: "Medium",
    timeToImplement: "4-5 weeks",
    roi: "190% ROI",
    technologies: ["Node.js", "OpenAI API", "MongoDB", "Redis", "React", "Webhook APIs"],
    flowData: {
      nodes: [
        {
          id: '1',
          type: 'input',
          data: { label: 'Content Strategy' },
          position: { x: 50, y: 100 },
        },
        {
          id: '2',
          data: { label: 'AI Content Generation' },
          position: { x: 250, y: 100 },
        },
        {
          id: '3',
          data: { label: 'Visual Creation' },
          position: { x: 450, y: 100 },
        },
        {
          id: '4',
          data: { label: 'Optimal Scheduling' },
          position: { x: 650, y: 100 },
        },
        {
          id: '5',
          data: { label: 'Multi-Platform Publishing' },
          position: { x: 250, y: 250 },
        },
        {
          id: '6',
          data: { label: 'Engagement Monitoring' },
          position: { x: 450, y: 250 },
        },
        {
          id: '7',
          data: { label: 'Auto Response' },
          position: { x: 650, y: 250 },
        },
        {
          id: '8',
          type: 'output',
          data: { label: 'Analytics Dashboard' },
          position: { x: 450, y: 350 },
        },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3' },
        { id: 'e3-4', source: '3', target: '4' },
        { id: 'e4-5', source: '4', target: '5' },
        { id: 'e5-6', source: '5', target: '6' },
        { id: 'e6-7', source: '6', target: '7' },
        { id: 'e6-8', source: '6', target: '8' },
      ],
    },
  },
];

export default flowsData;
